# cloudbuild.yaml
steps:
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        if ! grep -q "pytz" backend/requirements.txt; then
          echo "pytz" >> backend/requirements.txt
        fi

  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/superb-backend', '-f', 'backend/Dockerfile', 'backend']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/superb-backend']

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'superb-backend'
      - '--image'
      - 'gcr.io/$PROJECT_ID/superb-backend'
      - '--region'
      - 'asia-east1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--add-cloudsql-instances'
      - 'dogtor-454402:asia-east1:dogtor-dev'

options:
  default_logs_bucket_behavior: REGIONAL_USER_OWNED_BUCKET