// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDKhxOXPrnnOsI81BMxzedWDDrT6W7Il2U',
    appId: '1:1041765261654:web:93144c2086ce9295633446',
    messagingSenderId: '1041765261654',
    projectId: 'dogtor-454402',
    authDomain: 'dogtor-454402.firebaseapp.com',
    storageBucket: 'dogtor-454402.firebasestorage.app',
    measurementId: 'G-KQ2TB1DKP9',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBCciaIQe-DlrMfrZt3Molkn790rbaklc8',
    appId: '1:1041765261654:ios:eb13fd8bd048f0ec58b6f7',
    messagingSenderId: '1041765261654',
    projectId: 'dogtor-454402',
    storageBucket: 'dogtor-454402.firebasestorage.app',
    iosClientId: '1041765261654-hv85kemgu2pjrmclc66h0itpshrrk3p2.apps.googleusercontent.com',
    iosBundleId: 'com.dogtor.superbFlutterApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBCciaIQe-DlrMfrZt3Molkn790rbaklc8',
    appId: '1:1041765261654:ios:eb13fd8bd048f0ec58b6f7',
    messagingSenderId: '1041765261654',
    projectId: 'dogtor-454402',
    storageBucket: 'dogtor-454402.firebasestorage.app',
    iosClientId: '1041765261654-hv85kemgu2pjrmclc66h0itpshrrk3p2.apps.googleusercontent.com',
    iosBundleId: 'com.dogtor.superbFlutterApp',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCVEN9eLFYQGKes132ay_d34fuz-pcCUPc',
    appId: '1:1041765261654:android:9937081c3404210558b6f7',
    messagingSenderId: '1041765261654',
    projectId: 'dogtor-454402',
    storageBucket: 'dogtor-454402.firebasestorage.app',
  );

}