// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDKhxOXPrnnOsI81BMxzedWDDrT6W7Il2U',
    appId: '1:426092249907:web:93144c2086ce9295633446',
    messagingSenderId: '426092249907',
    projectId: 'dogtor-c33d4',
    authDomain: 'dogtor-c33d4.firebaseapp.com',
    storageBucket: 'dogtor-c33d4.firebasestorage.app',
    measurementId: 'G-KQ2TB1DKP9',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC08-ayj1WJn8FgaVi-Eq4gyB95pNPuTPI',
    appId: '1:426092249907:ios:d5f104285c62eff7633446',
    messagingSenderId: '426092249907',
    projectId: 'dogtor-c33d4',
    storageBucket: 'dogtor-c33d4.firebasestorage.app',
    iosClientId: '426092249907-e5ff9jmpceiads6n4sfkof2uemjcrhm5.apps.googleusercontent.com',
    iosBundleId: 'com.example.superbFlutterApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC08-ayj1WJn8FgaVi-Eq4gyB95pNPuTPI',
    appId: '1:426092249907:ios:aa594c3ce723ac5f633446',
    messagingSenderId: '426092249907',
    projectId: 'dogtor-c33d4',
    storageBucket: 'dogtor-c33d4.firebasestorage.app',
    iosClientId: '426092249907-olief71ue5k89idf9m1fpk05gqm3bs6l.apps.googleusercontent.com',
    iosBundleId: 'com.dogtor.superbFlutterApp',
  );
}
