name: Flutter CI/CD

on:
  push:
    branches: [ main ]
    paths:
      - 'frontend/superb_flutter_app/**'
      - '.github/workflows/flutter-ci-cd.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'frontend/superb_flutter_app/**'
      - '.github/workflows/flutter-ci-cd.yml'

env:
  FLUTTER_VERSION: '3.32.8'

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend/superb_flutter_app
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: ${{ env.FLUTTER_VERSION }}
        cache: true
    
    - name: Install dependencies
      run: flutter pub get
    
    - name: Verify formatting
      run: dart format --output=none --set-exit-if-changed .
    
    - name: Analyze project source
      run: flutter analyze --no-fatal-infos --no-fatal-warnings
    
    #- name: Run tests
    #  run: flutter test

  build-ios:
    name: Build iOS
    needs: test
    runs-on: macos-latest
    if: github.ref == 'refs/heads/main'
    defaults:
      run:
        working-directory: frontend/superb_flutter_app
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: ${{ env.FLUTTER_VERSION }}
        cache: true
    
    - name: Install Flutter dependencies
      run: flutter pub get
        
    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.2'
        bundler: 'latest'
        bundler-cache: true
        #working-directory: frontend/superb_flutter_app

    - name: Upgrade lockfile to Bundler 2
      working-directory: frontend/superb_flutter_app
      run: |
        gem install bundler -v 2.7.1
        bundle _2.7.1_ update --bundler

    #- name: Bundle install
    #  working-directory: frontend/superb_flutter_app
    #  run: bundle install --jobs 4 #bundle _2.7.1_ install --jobs 4
    
    - name: Install Fastlane dependencies
      working-directory: frontend/superb_flutter_app
      run: bundle _2.7.1_ install --jobs 4
    
    - name: Setup Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '15.2'
    
    - name: Build iOS with Fastlane (with signing)
      run: bundle exec fastlane ios build
      working-directory: frontend/superb_flutter_app
      env:
        MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
        APP_STORE_CONNECT_API_KEY_ID: ${{ secrets.APP_STORE_CONNECT_API_KEY_ID }}
        APP_STORE_CONNECT_ISSUER_ID: ${{ secrets.APP_STORE_CONNECT_ISSUER_ID }}
        APP_STORE_CONNECT_API_KEY: ${{ secrets.APP_STORE_CONNECT_API_KEY }}
    
    - name: Upload iOS build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ios-build
        path: |
          frontend/superb_flutter_app/build/Runner.ipa
          frontend/superb_flutter_app/build/Runner.app.dSYM.zip

  deploy-testflight:
    name: Deploy to TestFlight
    needs: build-ios
    runs-on: macos-latest
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    defaults:
      run:
        working-directory: frontend/superb_flutter_app
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Download iOS build artifacts
      uses: actions/download-artifact@v4
      with:
        name: ios-build
        path: frontend/superb_flutter_app/build
    
    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.2'
        bundler-cache: true
        working-directory: frontend/superb_flutter_app
    
    - name: Install Fastlane dependencies
      working-directory: frontend/superb_flutter_app
      run: bundle install --jobs 4
    
    - name: Deploy to TestFlight (upload only)
      run: bundle exec fastlane ios upload_testflight
      working-directory: frontend/superb_flutter_app
      env:
        APP_STORE_CONNECT_API_KEY_ID: ${{ secrets.APP_STORE_CONNECT_API_KEY_ID }}
        APP_STORE_CONNECT_ISSUER_ID: ${{ secrets.APP_STORE_CONNECT_ISSUER_ID }}
        APP_STORE_CONNECT_API_KEY: ${{ secrets.APP_STORE_CONNECT_API_KEY }}

  deploy-appstore:
    name: Deploy to App Store
    needs: build-ios
    runs-on: macos-latest
    if: github.ref == 'refs/heads/main' && github.event_name == 'push' && contains(github.event.head_commit.message, '[release]')
    defaults:
      run:
        working-directory: frontend/superb_flutter_app
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Download iOS build artifacts
      uses: actions/download-artifact@v4
      with:
        name: ios-build
        path: frontend/superb_flutter_app/build
    
    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.2'
        bundler-cache: true
        working-directory: frontend/superb_flutter_app
    
    - name: Install Fastlane dependencies
      working-directory: frontend/superb_flutter_app
      run: bundle install --jobs 4
    
    - name: Deploy to App Store (upload only)
      run: bundle exec fastlane ios upload_appstore
      working-directory: frontend/superb_flutter_app
      env:
        APP_STORE_CONNECT_API_KEY_ID: ${{ secrets.APP_STORE_CONNECT_API_KEY_ID }}
        APP_STORE_CONNECT_ISSUER_ID: ${{ secrets.APP_STORE_CONNECT_ISSUER_ID }}
        APP_STORE_CONNECT_API_KEY: ${{ secrets.APP_STORE_CONNECT_API_KEY }}
