name: Flutter CI/CD

on:
  push:
    branches: [ main ]
    paths:
      - 'frontend/superb_flutter_app/**'
      - '.github/workflows/flutter-ci-cd.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'frontend/superb_flutter_app/**'
      - '.github/workflows/flutter-ci-cd.yml'

env:
  FLUTTER_VERSION: '3.32.8'
  FASTLANE_USER: ${{ vars.FASTLANE_USER }}

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend/superb_flutter_app
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: ${{ env.FLUTTER_VERSION }}
        cache: true
    
    - name: Install dependencies
      run: flutter pub get
    
    - name: Verify formatting
      run: dart format --output=none --set-exit-if-changed .
    
    - name: Analyze project source
      run: flutter analyze --no-fatal-infos --no-fatal-warnings
    
    #- name: Run tests
    #  run: flutter test

  build-ios:
    name: Build iOS
    needs: test
    runs-on: macos-latest
    if: github.ref == 'refs/heads/main'
    defaults:
      run:
        working-directory: frontend/superb_flutter_app
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: ${{ env.FLUTTER_VERSION }}
        cache: true
    
    - name: Install dependencies
      run: flutter pub get
    
    - name: Setup Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '15.2'
    
    - name: Build iOS (no signing)
      run: flutter build ios --release --no-codesign
    
    - name: Upload iOS build
      uses: actions/upload-artifact@v4
      with:
        name: ios-build
        path: frontend/superb_flutter_app/build/ios/iphoneos/Runner.app

  deploy-ios:
    name: Deploy to App Store
    needs: build-ios
    runs-on: macos-latest
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    defaults:
      run:
        working-directory: frontend/superb_flutter_app
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: ${{ env.FLUTTER_VERSION }}
        cache: true
    
    - name: Install dependencies
      run: flutter pub get
    
    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.2'
        bundler-cache: true
        working-directory: frontend/superb_flutter_app
    
    - name: Deploy to App Store
      run: bundle exec fastlane ios deploy
      env:
        MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
        APP_STORE_CONNECT_API_KEY: ${{ secrets.APP_STORE_CONNECT_API_KEY }}
