source "https://rubygems.org"

ruby ">= 3.1.0"

gem "fastlane"
gem "cocoapods"
gem "activesupport", "~> 7.0"

plugins_path = File.join(File.dirname(__FILE__), 'fastlane', 'Pluginfile')
eval_gemfile(plugins_path) if File.exist?(plugins_path)
